### ISSUE TITLE
Make library less chatty

### ISSUE THREAD

**Issue by larskuhtz** [argumentcomputer/lurk-hs#13]
The library prints a lot of messages to the console, which is convenient for debugging and testing not wanted in production use.

Ideally, the library would accept some sort of handle or callback for logging.

Alternatively, the library may use an environment variable to enable log messages on the console. The default behavior (when the env variable is unset) should be that nothing is printed to the console (with the possible exception of fatal/crashing errors).

**Comment by huitseeker** [comment]
Fixed in https://github.com/argumentcomputer/sphinx/pull/193
The configuration to only see errors is `SP1_GO_LOG=error RUST_LOG=error my_executable`
